### ISSUE TITLE
Spaces in filenames

### ISSUE THREAD

**Issue by jchome** [Nexucis/ci-checkFiles#2]
When a filename contains spaces, the script doesn't applies well. For example, for the file "File with spaces.txt", it does 3 tests:
- "File"
- "with"
- "spaces.txt"
The result is that the script does not find these 3 files and fails on the test.

I've done a version that correct this case. Is it possible to give me the authorization to create a branch ?

**Comment by Nexucis** [comment]
You can create a fork of the repository and make a pull request after that :).

**Comment by jchome** [comment]
Thanks Augustin! That's done.

**Comment by Nexucis** [comment]
#3 merged. Thanks for your contribution :)
